### ISSUE TITLE
GScan 2.0 should be able to scan a 1.0 theme

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/gscan#116]
GScan 2.0 should be able to:

- scan a theme for Ghost 2.0 (latest)
- scan a theme for Ghost 1.0 with the help of a flag e.g. `gscan --v1`

The idea is that GScan is able to scan a "new" and a "previous" version of Ghost.
If we e.g. ship Ghost 3.0, GScan will scan latest (3.0) and 2.0.

GScan must provide a ruleset for both versions. Currently we are making use of a single `spec.js` file, which holds **most** of the rules. Some of the rules live inside the checkers, which should be moved into the `spec.js` file. 

## Which rules to apply on a 2.0 theme?

I think we have to apply all rules from 2.0 and 1.0 🤔 We just need to ensure that the GScan 2.0 branch doesn't have a rule, which conflicts for 1.0 and 2.0. Theoretical example: We have a deprecation rule in 1.0, which tells the user to use Y instead of X. And in 2.0 we tell the user to remove Y completely, because it's no longer supported. GScan should not show both warnings/errors.

## Tasks
- [x] make it possible to pass a version argument `--v1`, which will tell GScan to scan the theme based on Ghost 1.0 rules
- [x] add a very simple UI to choose latest or v1
- [x] merge into GScan 2.0 branch
- [x] output scanned version (see comment [here](https://github.com/TryGhost/gscan/pull/118#issuecomment-408552474) -> #128 
- [ ] Write logic to remove rules in a newer version (e. g. a prev. known helper should now be removed), see comment [here](https://github.com/TryGhost/gscan/pull/118#discussion_r207781870)
- [x] Central place to adjust the major version (similar to a config value) -> #127 
- [x] Make links to documentation dependent on the version (see comment [here](https://github.com/TryGhost/gscan/pull/118#discussion_r208211785)) -> #127

**Comment by AileenCGN** [comment]
I closed the opened PR #118 and updated the tasks in the original comment [here](https://github.com/TryGhost/gscan/issues/116#issue-342117951) to keep track of what's left to.

**Comment by AileenCGN** [comment]
> I can still find some https://themes.ghost.org/v1.25.0 links in the GScan 2.0 branch.

See https://github.com/TryGhost/gscan/pull/127

**Comment by AileenCGN** [comment]
I updated the tasks with the PRs where I fixed it

**Comment by kirrg001** [comment]
@AileenCGN I would suggest to raise a new issue and describe:

> Write logic to remove rules in a newer version (e. g. a prev. known helper should now be removed), see comment here

Because this issue is specific to GScan 2.0.
Then we can close this issue.

**Comment by AileenCGN** [comment]
@kirrg001 Sure thing. Have a have ready local solution for it already, but let's close this one in favour of #135

This issue was fixed with https://github.com/TryGhost/gscan/commit/9d5603caaea95f48f4293a9a34e60284b70eaacc and ba6b5116c5804ba4775a3b3243b3a56234a0d7f8
